### ISSUE TITLE
Include Detailed Version Information and Mode in Summary Sheet

### ISSUE THREAD

**Issue by YongGoose** [fosslight/fosslight_scanner#102]
**Is your feature request related to a problem? Please describe.**
FL Scanner only outputs its own version.

**Describe the solution you'd like**
The FL Scanner's summary sheet should be enhanced to include additional information. 
- Versions of the sub-packages: FL Source, FL Binary, and FL Dependency.
- The mode that has been selected.

**Comment by soimkim** [comment]
@YongGoose 님, 현재는 하기와 같이 Tool name, Tool version을 나누어 출력하고 있습니다. 
하위 pakcage인 FL Source, FL Binary, FL Dependency까지 출력하기 위해서는 Tool name, Tool version을 Tool info로 통합하고 출력이 필요합니다. 
AS-IS : 
<img width="850" alt="image" src="https://github.com/user-attachments/assets/912283a0-72d0-4609-a30b-50439d0ebced">
TO-BE: 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/01cc5e71-b08d-40d8-aab9-f4c244722239">
