### ISSUE TITLE
Add install guide for mac user

### ISSUE THREAD

**Issue by Sihan-Son** [fosslight/fosslight_scanner#106]
Fossligth scanner is not work just install with `pip` or `pip3`

After install with `pip` or `pip3` I faced import error is as follow.
`ImportError: failed to find libmagic. Check your installation`  

It can not fix `pip install magic` or `pip install libmagic`.

I fix it with brew.

Please add one line for mac user in install guide
`brew install libmagic`

**Comment by soimkim** [comment]
@Sihan-Son , 
This link, https://fosslight.org/fosslight-guide-en/scanner/etc/guide_virtualenv.html , provides guidance on what to pre-install.
In the [README](https://github.com/fosslight/fosslight_scanner/blob/main/README.md), it is a page linked to the 'How to install' section.
